# Generated by CogSol 0.2.0 on 2026-01-10 14:57
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateTopic(name='CogsolAPIsDocs', fields={'name': 'Cogsol APIs Docs'}, meta={'description': 'All documents related to the Cogsol APIs'}),
        migrations.CreateTopic(name='CogsolAPIsDocs/CognitiveModels', fields={'name': 'Cognitive API Models'}, meta={'description': 'All documents related to Cognitive API Models'}),
        migrations.CreateTopic(name='CogsolAPIsDocs/ContentModels', fields={'name': 'Content API Models'}, meta={'description': 'All documents related to Content API Models'}),
        migrations.CreateTopic(name='CogsolFrameworkDocs', fields={'name': 'Cogsol Framework Docs'}, meta={'description': 'All documents related to the Cogsol Framework'}),
        migrations.CreateRetrieval(name='cogsol_apis_docs_search', fields={'name': 'cogsol_apis_docs_search', 'topic': 'Cogsol APIs Docs', 'num_refs': 5, 'formatters': []}),
        migrations.CreateRetrieval(name='cogsol_framework_docs_search', fields={'name': 'cogsol_framework_docs_search', 'topic': 'Cogsol Framework Docs', 'num_refs': 5, 'formatters': []}),
    ]
