# Generated by CogSol 0.2.0 on 2026-01-10 15:18
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = False
    dependencies = [('data', '0001_initial')]
    operations = [
        migrations.CreateIngestionConfig(name='cogsol_framework_ingestion', fields={'name': 'cogsol_framework_ingestion', 'pdf_parsing_mode': 'manual', 'chunking_mode': 'ingestor', 'max_size_block': 1500, 'chunk_overlap': 0, 'separators': [], 'ocr': False, 'additional_prompt_instructions': '', 'assign_paths_as_metadata': False}),
    ]
