# Generated by CogSol 0.2.0 on 2026-01-10 16:12
from cogsol.db import migrations


class Migration(migrations.Migration):
    initial = False
    dependencies = [('data', '0002_auto_20260110_1518')]
    operations = [
        migrations.AlterField(model_name='cogsol_apis_docs_search', name='topic', value='CogsolAPIsDocs', entity='retrievals', scope='fields'),
        migrations.AlterField(model_name='cogsol_framework_docs_search', name='topic', value='CogsolFrameworkDocs', entity='retrievals', scope='fields'),
    ]
